<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Azure.Search.Documents" Version="11.7.0" />
    <PackageReference Include="LiteDB" Version="5.0.17" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.1" />
  </ItemGroup>

</Project>
